### PR TITLE
fix(scanner): support string format for 'repository' field in comparePayloads

### LINKED ISSUE #623: fix(scanner): support string format for 'repository' field in comparePayloads
### Context
While reviewing [comparePayloads.ts](cci:7://file:///c:/Users/Hp/OneDrive/Desktop/2026%20plan/scanner/workspaces/scanner/src/comparePayloads.ts:0:0-0:0), I noticed a `FIXME` comment highlighting that the `repository` field comparison doesn't currently handle string formats (shorthand repositories like `"github:user/repo"`).

### Problem
Currently, the [compareVersions](cci:1://file:///c:/Users/Hp/OneDrive/Desktop/2026%20plan/scanner/workspaces/scanner/src/comparePayloads.ts:150:0-186:1) function attempts to compare `repository` by looking for `.type` or `.url` properties:

```ts
// workspaces/scanner/src/comparePayloads.ts
repository: compareObjects("type", version.repository, comparedVersion.repository)
  ?? compareObjects("url", version.repository, comparedVersion.repository),

### PR DESCRIPTION
**Pull request by 7amed3li**
**Closes #623**

### CODE REVIEW

File: workspaces/scanner/src/comparePayloads.ts [hunk 1]
```diff
@@ -312,3 +310,22 @@ export function arrayOfObjectsDiffByKey<T extends Record<string, any>>(
...
+  if (typeof original === "undefined" && typeof toCompare === "undefined") {
+    return undefined;
+  }
+
+  const isOriginalString = typeof original === "string";
+  const isComparedString = typeof toCompare === "string";
+
+  if (isOriginalString || isComparedString) {
+    return compareValues<string | undefined>(original as string | undefined, toCompare as string | undefined);
+  }
```
Comment (fraxken) [inline workspaces/scanner/src/comparePayloads.ts]: Are type cast really required here? Feel like the type should be properly narrowed because of the typeof

**Comment by 7amed3li** [comment]
Small hiccup while rebasing on my side — all good now. Thanks for your patience.
